services:
  app:
    build: .
    container_name: ms_ai
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: ms_ai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Mapping host port 5433 to container port 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


  alembic:
    build: .
    container_name: alembic_migrations
    command: alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env

volumes:
  postgres_data: