"""Add last_updated column to ReceiptApproverResponse

Revision ID: 16ed6afdb39d
Revises: 
Create Date: 2024-08-28 05:29:02.033325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ed6afdb39d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_approver_responses', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'receipt_approver_responses', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt_approver_responses', type_='unique')
    op.drop_column('receipt_approver_responses', 'last_updated')
    # ### end Alembic commands ###
