"""Initial migration

Revision ID: 5f8497cad6bd
Revises:
Create Date: 2024-10-16 09:28:55.590173

"""

import sqlalchemy as sa

from alembic import op
from app.config.guid import GUID

# revision identifiers, used by Alembic.
revision = "5f8497cad6bd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipt_approver_responses",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("client", sa.String(), nullable=False),
        sa.Column("ocr_raw", sa.JSON(), nullable=False),
        sa.Column("processed", sa.JSON(), nullable=False),
        sa.Column("user_input_data", sa.JSON(), nullable=False),
        sa.Column("receipt_classifier_response", sa.JSON(), nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receipt_approver_responses")
    # ### end Alembic commands ###
