"""Add receipt classifier response

Revision ID: 85269fcaf54a
Revises: 16ed6afdb39d
Create Date: 2024-08-28 13:43:02.205439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85269fcaf54a'
down_revision = '16ed6afdb39d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_approver_responses', sa.Column('receipt_classifier_response', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_approver_responses', 'receipt_classifier_response')
    # ### end Alembic commands ###
